
import java.sql.Connection;
import java.sql.DriverManager;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author DELL LAPTOP
 */
public class Main_Frame extends javax.swing.JFrame {

    Connection con;
    String username;

    public Main_Frame(String u) {
        username = u;
        
        initComponents();
        try {
            Class.forName("oracle.jdbc.OracleDriver");
            //Connection String
            String r1 = "jdbc:oracle:thin:@localhost:1521:";
            con = DriverManager.getConnection(r1, "ekam", "ekam");

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, e.getMessage());
            dispose();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dp = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuChangePassword = new javax.swing.JMenuItem();
        mnuLogOut = new javax.swing.JMenuItem();
        mnuExit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mnuManageCompany = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        mnuManageProducts = new javax.swing.JMenuItem();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jMenu5 = new javax.swing.JMenu();
        mnuBill = new javax.swing.JCheckBoxMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout dpLayout = new javax.swing.GroupLayout(dp);
        dp.setLayout(dpLayout);
        dpLayout.setHorizontalGroup(
            dpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        dpLayout.setVerticalGroup(
            dpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        jMenu1.setText("General");

        mnuChangePassword.setText("Change Password");
        mnuChangePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuChangePasswordActionPerformed(evt);
            }
        });
        jMenu1.add(mnuChangePassword);

        mnuLogOut.setText("Log Out");
        mnuLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuLogOutActionPerformed(evt);
            }
        });
        jMenu1.add(mnuLogOut);

        mnuExit.setText("Exit");
        mnuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuExitActionPerformed(evt);
            }
        });
        jMenu1.add(mnuExit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Employee");

        jMenuItem1.setText("Manage Employee");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Companies");

        mnuManageCompany.setText("Manage Companies");
        mnuManageCompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuManageCompanyActionPerformed(evt);
            }
        });
        jMenu3.add(mnuManageCompany);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Products");

        mnuManageProducts.setText("Manage Products");
        mnuManageProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuManageProductsActionPerformed(evt);
            }
        });
        jMenu4.add(mnuManageProducts);

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("Company-Product");
        jCheckBoxMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem1ActionPerformed(evt);
            }
        });
        jMenu4.add(jCheckBoxMenuItem1);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Orders");

        mnuBill.setSelected(true);
        mnuBill.setText("Bill");
        mnuBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuBillActionPerformed(evt);
            }
        });
        jMenu5.add(mnuBill);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dp)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dp)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void mnuChangePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuChangePasswordActionPerformed
        changepassword k = new changepassword(con, username);
        k.setVisible(true);
        dp.add(k);
    }//GEN-LAST:event_mnuChangePasswordActionPerformed

    private void mnuLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuLogOutActionPerformed
        JOptionPane.showMessageDialog(this, "Logout Successful");
        dispose();
        Main_Login k = new Main_Login();
        k.setVisible(true);
    }//GEN-LAST:event_mnuLogOutActionPerformed

    private void mnuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mnuExitActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
       manageemployee k = new manageemployee(con);
        k.setVisible(true);
        dp.add(k);

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void mnuManageCompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuManageCompanyActionPerformed
       managecompany k = new managecompany(con);
       k.setVisible(true);
       dp.add(k);
              
    }//GEN-LAST:event_mnuManageCompanyActionPerformed

    private void mnuManageProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuManageProductsActionPerformed
        manageproduct k = new manageproduct(con);
       k.setVisible(true);
       dp.add(k);
    }//GEN-LAST:event_mnuManageProductsActionPerformed

    private void mnuBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuBillActionPerformed
       bill k = new bill(con);
       k.setVisible(true);
       dp.add(k);
    }//GEN-LAST:event_mnuBillActionPerformed

    private void jCheckBoxMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem1ActionPerformed
       mapping k = new mapping(con, dp);
       k.setVisible(true);
       dp.add(k);
    }//GEN-LAST:event_jCheckBoxMenuItem1ActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane dp;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JCheckBoxMenuItem mnuBill;
    private javax.swing.JMenuItem mnuChangePassword;
    private javax.swing.JMenuItem mnuExit;
    private javax.swing.JMenuItem mnuLogOut;
    private javax.swing.JMenuItem mnuManageCompany;
    private javax.swing.JMenuItem mnuManageProducts;
    // End of variables declaration//GEN-END:variables
}
